version: 2
services:
  - type: web
    name: social-trends-api
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
databases:
  - name: social-trends-db
    databaseName: social_trends
    user: social_trends_user
    plan: free
